name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # 'macos-latest' for MacOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          
      - name: Run Playwright tests
        run: |
          npm run test  

      - name: Install Allure commandline
        run: |
          npm install -g allure-commandline --save-dev
          
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean  

      - name: Check Allure results
        run: |
          if [ ! -d allure-results ]; then
            echo "allure-results directory does not exist"
            exit 1
          fi
          echo "allure-results directory exists"

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-results  

      - name: Serve Allure report
        run: |
          allure serve allure-results  
