name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # O usa 'macos-latest' si estás en MacOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          
      - name: Run Playwright tests
        run: |
          npm run test  # Ejecuta los tests de Playwright

      - name: Install Allure commandline
        run: |
          npm install -g allure-commandline --save-dev
          
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean  # Genera el reporte de Allure

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-results  # Usamos allure-results aquí, no allure-report

      - name: Serve Allure report
        run: |
          allure serve allure-results  # Sirve el reporte en el servidor local
