name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  #  'macos-latest' macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
          
      - name: Run Playwright tests
        run: npm run test  

      - name: Debug workspace structure
        run: ls -R  # Check structure of files

      - name: Check if Allure results exist before generating the report
        run: |
          if [ ! -d allure-results ]; then
            echo "❌ ERROR: allure-results directory does not exist!"
            exit 1
          fi
          echo "✅ allure-results directory found!"

      - name: Install Allure commandline
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: allure generate allure-results --clean  

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results